import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import Whisper from './api/whisper';

import { Configuration, OpenAIApi } from 'openai';

// setting up authorized access to the Dall-e API
const configuration = new Configuration({
  apiKey: process.env.DALLE_API_KEY,
});
const openai = new OpenAIApi(configuration);

export default function Home() {

  const [text, setText] = useState('');
  const [response, setResponse] = useState('');

  // prototype for text to speech
  useEffect(() => {
    const synth = window.speechSynthesis;
    const voices = synth.getVoices(); 
    const sayThis = new SpeechSynthesisUtterance(response); 
    sayThis.voice = voices[60]; // 0, 17, 10, 60, 58, 53, 51, 50, 49, 39, 33, 26
    synth.speak(sayThis);
  }, [response]);

  const sendQuery = async (prompt: string): Promise<void> => {
    const completion: any = await openai.createCompletion({
      model: "text-davinci-003",
      prompt,
      max_tokens: 250,
    })
    setResponse(await completion.data.choices[0].text);
  }

  useEffect(() => {
    if (text === "") {
      return;
    }
    console.log(text);
    sendQuery(text);
    setText("");
    }, [text]);

  useEffect(() => {
    console.log(response);
  }, [response])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Whisper setText={setText}>text</Whisper>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
